name: Release

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version-file: "go.mod"

            - name: Print Go version
              run: go version

            - name: Build
              run: go build -v -o crawlarr -ldflags "-s -w" ./...

            - name: Publish Artifact
              if: ${{ success() }}
              uses: actions/upload-artifact@master
              with:
                  name: crawlarr
                  path: crawlarr

            - name: Publish release
              if: ${{ success() }}
              uses: ncipollo/release-action@v1
              with:
                  commit: master
                  tag: latest
                  body: "See [CHANGELOG](/CHANGELOG.md)."
                  allowUpdates: true
                  makeLatest: true
                  artifacts: "crawlarr"
                  token: ${{ secrets.GITHUB_TOKEN }}
